server:
  port: 7001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@eureka1.com:7001/eureka/
#  server:
#    enable-self-preservation: false


spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: http://localhost:80/
  application:
    name: eureka-server

management:
  endpoints:
    web:
      exposure:
        # 这是一个Set<String>
        include: "*"
  endpoint:
    health:
      show-details: always