server:
  port: 7001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1.com:7001/eureka
  # \u5173\u95ED\u81EA\u6211\u4FDD\u62A4\uFF1A\u9ED8\u8BA4\u5F00\u542F
  server:
    enable-self-preservation: false


# \u5B89\u5168\u8BA4\u8BC1
spring:
  security:
    user:
      name: admin
      password: admin

