server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1.com:7001/eureka/

# 配置从git上拉取配置文件
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nishimiyaskii/SpringCloud-Config-Center.git
      label: master
  application:
    name: config-center-server