server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/
    # \u4E0A\u62A5\u670D\u52A1\u7684\u771F\u5B9E\u72B6\u6001\uFF1A\u5373\u8BE5\u670D\u52A1\u53EF\u8DF3\u8FC7Eureka\u7684\u81EA\u6211\u4FDD\u62A4\u673A\u5236
    healthcheck:
      enabled: true
  instance:
    hostname: eureka1.com

spring:
  application:
    name: consumer

management:
    #\u5F00\u542F\u4E0A\u62A5\u6240\u6709\u7AEF\u70B9
#  endpoints:
#    web:
#      exposure:
#        include: *
  # \u5F00\u542F\u8FDC\u7A0B\u4E0B\u7EBF\u670D\u52A1
  endpoint:
    shutdown:
      enabled: true




