server:
  port: 82
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1.com:7001/eureka/
  instance:
    hostname: eureka1.com
spring:
  application:
    name: springcloud-consumer
  boot:
    admin:
      client:
        url: http://localhost:80/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
