server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1.com:7001/eureka/
  instance:
    hostname: eureka1.com
spring:
  application:
    name: feign-provider


