server:
  port: 8001
eureka:
  client:
    service-url:
      # \u524D\u7F00\u8868\u793AEureka Server\u542F\u52A8\u4E86\u5B89\u5168\u8BA4\u8BC1\u3002\u9700\u8981\u4F7F\u7528\u8D26\u53F7\u5BC6\u7801\u624D\u80FD\u8FDB\u884C\u670D\u52A1\u6CE8\u518C
      defaultZone: http://admin:admin@eureka1.com:7001/eureka/
  instance:
    hostname: eureka1.com
spring:
  application:
    name: provider
